### ISSUE TITLE
Issue while running prettier-stylelint via CLI

### ISSUE THREAD

**Issue by AjayPoshak** [hugomrdias/prettier-stylelint#15]
When I try to run prettier-stylelint via CLI ```prettier-stylelint```, I get the following error:

```
module.exports.silent = moduleId => resolveFrom.silent(process.cwd(), moduleId);
                                                ^

TypeError: resolveFrom.silent is not a function
    at Function.module.exports.silent.moduleId [as silent] (/Users/ajayposhak/Sites/M6/site/node_modules/resolve-cwd/index.js:5:49)
    at module.exports.filename (/Users/ajayposhak/Sites/M6/site/node_modules/import-local/index.js:10:31)
    at Object.<anonymous> (/Users/ajayposhak/Sites/M6/site/node_modules/prettier-stylelint/cli.js:8:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

**Comment by sparkeplug** [comment]
Hey,

Can you please tell me how did u run the "prettier-stylelint" command in cli ?

I'm using windows, and ive installed "prettier-stylelint" in my project as dev dependency.

When i use the command "prettier-stylelint" in the root folder of my project in Command Prompt ( Windows ) it says command not found. 

Can you please explain how to access the CLI ?

**Comment by br4nnigan** [comment]
@sparkeplug 

`node node_modules/prettier-stylelint/src/cli.js`

at least that's the way I figured out, on MacOS, but should work in Windows, too.
