### ISSUE TITLE
Undefined rule font-family-no-missing-generic-family-keyword 

### ISSUE THREAD

**Issue by eldair** [hugomrdias/prettier-stylelint#8]
Started getting error `Undefined rule font-family-no-missing-generic-family-keyword ` on format after updating `stylelint-config-standard`, probably outdated stylelint version?

**Comment by mstanaland** [comment]
I'm trying to get started with prettier-stylelint, and I'm getting the same error. Was thinking I had a bad config, but maybe there is bug or incompatible versions.

My stylelint.config.js is pretty basic:
```
module.exports = {
  extends: [
    "stylelint-config-recommended-scss",
    "./node_modules/prettier-stylelint/config.js"
  ]
};
```

And here's the error it throws for each file:
```
Error: Undefined rule font-family-no-missing-generic-family-keyword
    at module.exports (/Users/mstanaland/Desktop/account-react/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at Object.keys.forEach.ruleName (/Users/mstanaland/Desktop/account-react/node_modules/stylelint/lib/augmentConfig.js:278:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/Users/mstanaland/Desktop/account-react/node_modules/stylelint/lib/augmentConfig.js:274:29)
    at augmentConfigBasic.then.then.then.then.augmentedConfig (/Users/mstanaland/Desktop/account-react/node_modules/stylelint/lib/augmentConfig.js:83:12)
    at <anonymous>
```

**Comment by jeddy3** [comment]
Try [`npm --depth 1 update`](https://docs.npmjs.com/cli/update).

`font-family-no-missing-generic-family-keyword` was introduced in [`stylelint@8.3.0`](https://github.com/stylelint/stylelint/releases/tag/8.3.0) and this package [does have a dependency range that includes that version](https://github.com/hugomrdias/prettier-stylelint/blob/master/package.json#L55).

(This probably won't work if use `yarn` as the lockfile [pins stylelint to `8.1.1`](https://github.com/hugomrdias/prettier-stylelint/blob/master/yarn.lock#L4276). I believe a new version of this package will need to be published if it wishes to be compatible with the stylelint version of `config-standard` and `config-recommended`.)

**Comment by MarkSky** [comment]
I have the same error :`Undefined rule font-family-no-missing-generic-family-keyword`, when set` font-family-no-missing-generic-family-keyword": true`, in .stylelintrc file.

**Comment by timhecker** [comment]
Any news about this?

**Comment by eldair** [comment]
This is a huge pain, we have to manually run `npm --depth 1 update` each time a parent package updates.

**Comment by timhecker** [comment]
Thanks, but I'm a `yarn` user: I'm waiting for some update in VScode stylelint extension.
